### ISSUE TITLE
[ROS2] [RQT_PUBLISHER] Traceback when closing/exiting

### ISSUE THREAD

**Issue by Karsten1987** [ros-visualization/rqt_publisher#11]
When using `rqt_publisher` under dashing, I get a traceback when closing the application on OSX. This might be related to breaking changes in dashing related to passing the context object to `rcl_init()`. 
See here: https://github.com/ros2/rcl/blob/master/rcl/include/rcl/init.h#L82 and the related PR: https://github.com/ros2/rcl/pull/336

```
Traceback (most recent call last):
  File "/Users/karsten/workspace/osrf/ros2_full/build/rqt_gui_py/src/rqt_gui_py/rclpy_spinner.py", line 32, in run
    executor.spin_once(timeout_sec=1.0)
  File "/Users/karsten/workspace/osrf/ros2_full/install/lib/python3.7/site-packages/rclpy/executors.py", line 695, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/Users/karsten/workspace/osrf/ros2_full/install/lib/python3.7/site-packages/rclpy/executors.py", line 649, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/Users/karsten/workspace/osrf/ros2_full/install/lib/python3.7/site-packages/rclpy/executors.py", line 532, in _wait_for_ready_callbacks
    self._context.handle)
RuntimeError: Failed to initialize wait set: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /Users/karsten/workspace/osrf/ros2_full/src/ros2/rcl/rcl/src/rcl/wait.c:130
```

This issue might be one example for branching out to `dashing-devel` as described here: https://github.com/ros-visualization/rqt_publisher/issues/10

**Comment by Karsten1987** [comment]
closing this as the source of issue lies in `rqt_gui_py`, see https://github.com/ros-visualization/rqt/issues/198
