### ISSUE TITLE
ROS2: Publish an array with rqt

### ISSUE THREAD

**Issue by giwrgosg** [ros-visualization/rqt_publisher#23]
Hi everyone, I have been using rqt to publish messages to test my applications, however I still haven't found a way to publish a message that includes an array.
In my custom message I have a variable size array declared as uint8[]. I notice in rqt that the expected type is "sequence".
I have tried different expressions, but couldn't figure out the correct one. Could someone provide an example please?

**Comment by RyanDelGizzi** [comment]
If we assume [get_slot_types]() functions correctly, then [my fix here](https://github.com/RyanDelGizzi/rqt_publisher/commit/ead7da24e879a06e087fa96aaa4255113caec990) allows us to publish arrays.  However, as mentioned in [this related ticket](https://github.com/ros-visualization/rqt/issues/244), a much larger PR should probably be merged first, before addressing this issue. 

If anyone has any guidance on the guidance to help get these changes through, I'll be happy to help where fit.

**Comment by wienans** [comment]
As porposed in #34 i tried to compile the rolling release and still got the error
```[ERROR] [1673338979.392064043] [get_message_class]: Malformed message_type: sequence<uint32>
Traceback (most recent call last):
  File "/colcon_ws/install/rqt_publisher/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 158, in change_publisher
    new_text = handler(self._publishers[publisher_id], topic_name, new_value)
  File "/colcon_ws/install/rqt_publisher/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 257, in _change_publisher_expression
    success, _ = self._evaluate_expression(computed_expression, slot_type)
  File "/colcon_ws/install/rqt_publisher/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 376, in _evaluate_expression
    if successful_eval and isinstance(value, slot_type):
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```
after i typed `array('I',[1,2,3])`
or got this error if i used `array.array('I',[1,2,3])`

```
[ERROR] [1673339078.788973249] [get_message_class]: Malformed message_type: sequence<uint32>
Python eval failed for expression "array.array('I',[1,2,3])" with an exception "type object 'array.array' has no attribute 'array'"
Publisher._evaluate_expression(): failed to evaluate expression: "array.array('I',[1,2,3])" as Python type "None"
Traceback (most recent call last):
  File "/colcon_ws/install/rqt_publisher/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 158, in change_publisher
    new_text = handler(self._publishers[publisher_id], topic_name, new_value)
  File "/colcon_ws/install/rqt_publisher/lib/python3.10/site-packages/rqt_publisher/publisher.py", line 274, in _change_publisher_expression
    user_expression, slot_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?
```
If i understood the other Issue #34 correctly this should have worked? I am using a UInt32 MultiArray

**Comment by baldhat** [comment]
There is still no way, or at least no documented way on doing this. Can anybody help out?

**Comment by egordon** [comment]
Right now there is no way to do this since `rqt_publisher` does not support the `array.array` type and the common libraries don't support `sequence<X>` builtin types. I just submitted #39 to `humble` to fix both of these.

If you want to use it, strings are represented as normal lists, e.g.: `["joint_1", "joint_2"]`
Numerical arrays are represented as array types, e.g.: `array('d', [5.5, 4.5])` or `array('i', [3, 2])`. 

See a complete list of numerical typecodes at https://docs.python.org/3/library/array.html
