### ISSUE TITLE
ROS2 - Windows 10 : AttributeError: module 'numpy' has no attribute 'float128'

### ISSUE THREAD

**Issue by jonathanTIE** [ros-visualization/rqt_publisher#31]
On Rqt with Win10, trying to open rqt_publisher yields this error and doesn't work :  

> PluginManager._load_plugin() could not load plugin "rqt_publisher/Publisher":
Traceback (most recent call last):
  File "c:\opt\ros\galactic\x64\lib\site-packages\qt_gui\plugin_handler.py", line 102, in load
    self._load()
  File "c:\opt\ros\galactic\x64\lib\site-packages\qt_gui\plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "c:\opt\ros\galactic\x64\lib\site-packages\qt_gui\composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "c:\opt\ros\galactic\x64\lib\site-packages\qt_gui\composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "c:\opt\ros\galactic\x64\lib\site-packages\rqt_gui_py\ros_py_plugin_provider.py", line 64, in load
    return super(RosPyPluginProvider, self).load(plugin_id, ros_plugin_context)
  File "c:\opt\ros\galactic\x64\lib\site-packages\qt_gui\composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "c:\opt\ros\galactic\x64\lib\site-packages\rqt_gui\ros_plugin_provider.py", line 91, in load
    raise e
  File "c:\opt\ros\galactic\x64\lib\site-packages\rqt_gui\ros_plugin_provider.py", line 80, in load
    module = __builtin__.__import__(
  File "c:\opt\ros\galactic\x64\lib\site-packages\rqt_publisher\publisher.py", line 60, in <module>
    numpy.float16, numpy.float32, numpy.float64, numpy.float128,
  File "c:\opt\ros\galactic\x64\lib\site-packages\numpy\__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'

To solve it, I had to remove in `rqt_publisher/src/rqt_publisher/publisher.py` at line 60 numpy.float128, and it seems to run smoothly without it.

> try:
    import numpy
    _numeric_types += [
        numpy.int8, numpy.int16, numpy.int32, numpy.int64,
        numpy.float16, numpy.float32, numpy.float64,
    ]

**Comment by jonathanTIE** [comment]
My binary didn't contain the last versions which corrected these issues.
